### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by karmanyaahm** [karmanyaahm/miniflux-compatible-mobile-app#1]
So there will probably be 5 stages

- [ ] Something that abstracts out the Miniflux (and in the future possibly other) apis #2
- [ ] Something that manages the data 'fetching' between 1 and 3 #3
- [ ] Something that abstracts out the database - including several data models probably #4
- [ ] Something that abstracts out whatever the UI might want from the database #5
- [ ] the UI #6
